import { defineRouteConfig } from '@medusajs/admin-sdk';
import { Button,Container,Heading,Input,Text,toast } from '@medusajs/ui';
import { useEffect,useState } from 'react';
import type { StorefrontSettings } from '@pk/contracts';
async function api(path:string,body?:unknown){const response=await fetch(path,{credentials:'include',method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error?.message??result.message??'Request failed.');return result.data??result;}
export default function StorefrontPage(){
 const [channel,setChannel]=useState('');const [settings,setSettings]=useState<StorefrontSettings>({banners:[],cities:[],inquiry_enabled:false});const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(true);const [error,setError]=useState('');
 const [coupons,setCoupons]=useState<{code:string;discount_pkr:number;minimum_advance_pkr:number;max_redemptions:number;redemptions:number;active:boolean;expires_at:string|null}[]>([]);
 async function reload(id:string){const [content,codes]=await Promise.all([api('/admin/storefront-settings?channel_id='+encodeURIComponent(id)),api('/admin/inquiry-coupons?channel_id='+encodeURIComponent(id))]);setSettings(content.configuration);setRevision(content.revision);setCoupons(codes.coupons);}
 useEffect(()=>{void(async()=>{try{const result=await api('/admin/sales-channels?limit=100');const selected=result.sales_channels.find((c:{name:string})=>c.name.toUpperCase()==='FONEKIST');if(!selected)throw new Error('FONEKIST sales channel was not found.');setChannel(selected.id);await reload(selected.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}})();},[]);
 async function save(){setBusy(true);setError('');try{await api('/admin/storefront-settings',{channel_id:channel,revision,configuration:settings});await reload(channel);toast.success('Storefront settings saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Container><Heading>Fonekist storefront</Heading><Text className="mt-2">Manage inquiry availability, Karachi delivery areas, banners and coupons. Product descriptions, photos, categories and brands use Products and Product Categories; installment amounts use Installment Schedules.</Text>{error&&<Text role="alert" className="mt-4 text-ui-fg-error">{error}</Text>}
 <fieldset disabled={busy||!channel} className="mt-6 space-y-6"><label className="flex gap-3"><input type="checkbox" checked={settings.inquiry_enabled} onChange={e=>setSettings({...settings,inquiry_enabled:e.target.checked})}/>Accept inquiries</label>
 <section><Heading level="h2">Delivery coverage</Heading>{settings.cities.map((city,index)=><div key={index} className="mt-3 grid gap-3"><label>City<Input value={city.name} onChange={e=>setSettings({...settings,cities:settings.cities.map((c,i)=>i===index?{...c,name:e.target.value}:c)})}/></label><label>Areas, one per line<textarea className="mt-2 w-full rounded border p-3" rows={7} value={city.areas.join('\n')} onChange={e=>setSettings({...settings,cities:settings.cities.map((c,i)=>i===index?{...c,areas:e.target.value.split('\n')}:c)})}/></label></div>)}</section>
 <section><Heading level="h2">Homepage banners</Heading><Text>Use HTTPS images from durable storage. Leave the list empty to use the existing product banners.</Text>{settings.banners.map((banner,index)=><div key={banner.id} className="mt-4 space-y-3 rounded border p-4">{(['eyebrow','headline','support','image','imageAlt','href','cta'] as const).map(field=><label key={field} className="block">{{eyebrow:'Small heading',headline:'Headline',support:'Description',image:'Image URL',imageAlt:'Image description',href:'Link path',cta:'Button text'}[field]}<Input value={banner[field]} onChange={e=>setSettings({...settings,banners:settings.banners.map((b,i)=>i===index?{...b,[field]:e.target.value}:b)})}/></label>)}<label className="flex gap-2"><input type="checkbox" checked={banner.active} onChange={e=>setSettings({...settings,banners:settings.banners.map((b,i)=>i===index?{...b,active:e.target.checked}:b)})}/>Visible</label><Button variant="danger" onClick={()=>setSettings({...settings,banners:settings.banners.filter((_,i)=>i!==index)})}>Remove banner</Button></div>)}<Button className="mt-3" disabled={settings.banners.length>=10} onClick={()=>setSettings({...settings,banners:[...settings.banners,{id:crypto.randomUUID(),eyebrow:'Fonekist',headline:'',support:'',image:'',imageAlt:'',href:'/phones',cta:'Browse phones',active:true}]})}>Add banner</Button></section>
 <div className="flex gap-3"><Button onClick={save}>Save storefront</Button><Button variant="secondary" onClick={()=>void reload(channel).catch(e=>setError(e.message))}>Reload saved settings</Button></div>
 </fieldset>
 <section className="mt-8"><Heading level="h2">Inquiry coupons</Heading><Text>Fixed rupee discount on the total advance. Each accepted inquiry uses one redemption. Closing an inquiry does not restore it.</Text>
 <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);try{await api('/admin/inquiry-coupons',{channel_id:channel,code:data.get('code'),discount_pkr:Number(data.get('discount')),minimum_advance_pkr:Number(data.get('minimum')),max_redemptions:Number(data.get('maximum')),active:data.get('active')==='on',expires_at:data.get('expires')?new Date(String(data.get('expires'))).toISOString():null});await reload(channel);form.reset();toast.success('Coupon saved.');}catch(error){setError((error as Error).message);}finally{setBusy(false);}}}>
 <label>Code<Input name="code" required minLength={3} maxLength={40}/></label><label>Discount (Rs)<Input name="discount" type="number" min={1} required/></label><label>Minimum advance (Rs)<Input name="minimum" type="number" min={0} defaultValue={0} required/></label><label>Maximum redemptions<Input name="maximum" type="number" min={1} required/></label><label>Expires at (your local time)<Input name="expires" type="datetime-local"/></label><label className="flex items-center gap-3"><input type="checkbox" name="active" defaultChecked/>Enabled</label><Button type="submit" disabled={busy||!channel}>Save coupon</Button></form>
 <ul className="mt-4 space-y-3">{coupons.map(c=><li key={c.code} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><Text>{c.code}: Rs {c.discount_pkr.toLocaleString()} off; minimum Rs {c.minimum_advance_pkr.toLocaleString()}; {c.redemptions}/{c.max_redemptions} used; {c.active?'enabled':'disabled'}{c.expires_at?`; expires ${new Date(c.expires_at).toLocaleString()}`:''}</Text><Button variant="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/admin/inquiry-coupons',{channel_id:channel,...c,active:!c.active});await reload(channel);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}}>{c.active?'Disable':'Enable'}</Button></li>)}</ul>
 </section></Container>;
}
export const config=defineRouteConfig({label:'Fonekist Storefront'});
