import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } });
const msgs = [];
p.on("pageerror", (e) => msgs.push("PAGEERROR: " + (e.stack || e.message).slice(0, 900)));
p.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") msgs.push(m.type().toUpperCase() + ": " + m.text().slice(0, 900)); });
await p.goto("http://localhost:3001/", { waitUntil: "networkidle", timeout: 90000 });
await p.waitForTimeout(3000);
console.log(msgs.length ? msgs.join("\n---\n") : "no messages");
await b.close();
