import type { NextConfig } from "next";

/**
 * The exact hosts next/image may fetch from.
 *
 * A wildcard hostname here turns the image endpoint into an open proxy: anyone can pass any
 * URL and have this server fetch and re-serve it, spending our bandwidth and reaching
 * whatever the server can reach. So both entries are single, explicitly configured origins.
 *
 * `NEXT_PUBLIC_MEDIA_HOST` is the CDN (ADR-012), HTTPS only.
 * `NEXT_PUBLIC_MEDIA_BASE_URL` is the origin actually serving catalog media, which in local
 * development is the other storefront on plain HTTP; see `src/lib/media.ts` for why that
 * seam exists. Parsed rather than pattern-matched so a malformed value fails loudly at
 * config load instead of silently allowing nothing.
 */
function buildRemotePatterns() {
  const patterns: { protocol: "http" | "https"; hostname: string; port?: string }[] = [];

  if (process.env.NEXT_PUBLIC_MEDIA_HOST) {
    patterns.push({ protocol: "https", hostname: process.env.NEXT_PUBLIC_MEDIA_HOST });
  }

  const base = process.env.NEXT_PUBLIC_MEDIA_BASE_URL;
  if (base) {
    const url = new URL(base);
    patterns.push({
      protocol: url.protocol === "http:" ? "http" : "https",
      hostname: url.hostname,
      ...(url.port ? { port: url.port } : {}),
    });
  }

  return patterns;
}

const config: NextConfig = {
  reactStrictMode: true,

  typedRoutes: true,

  /*
   * Static generation, sized for the machine that actually runs it.
   *
   * Next sizes its prerender pool from the reported core count, which on Render's free
   * instance meant 25 worker processes fighting over 0.1 of a CPU for 22 pages. Pages that
   * do no data fetching at all, `/_not-found` among them, then missed the 60 second budget
   * and failed the build. One worker builds them in sequence instead: slower on a big
   * machine, and the only thing that finishes on a small one.
   *
   * The longer budget is for the backend rather than the CPU. Every page renders the header
   * and footer, both of which read the brand list, and a free-tier backend that is cold or
   * mid-redeploy can spend the full 8 second client timeout before the page gives up on it.
   */
  experimental: { cpus: 1 },
  staticPageGenerationTimeout: 180,

  // FONEKIST documents its own conventions in CLAUDE.md; Next's generated agent files
  // would duplicate and contradict them.
  agentRules: false,

  images: {
    /*
     * Product photography is already stored as web-sized JPGs in `public/media`. Running
     * every tile through Next's on-demand transformer creates a 24-request CPU spike on
     * Render's 0.1-CPU free instance and can make the whole storefront time out. Serving
     * the same committed files directly keeps the visual output intact and makes catalog
     * pages cheap enough for the free tier.
     */
    unoptimized: true,

    // Newest-first, so browsers get the smallest file they can decode (PERF-002).
    formats: ["image/avif", "image/webp"],

    /*
     * Only the configured media host may be optimised. A wildcard hostname here turns the
     * image endpoint into an open proxy: anyone can pass any HTTPS URL and have this server
     * fetch and re-serve it. The host is configuration, so a real CDN is an environment
     * change rather than a code change (ADR-012).
     */
    remotePatterns: buildRemotePatterns(),

    /*
     * next/image refuses to fetch an upstream image whose hostname resolves to a private
     * IP, because that is the shape of an SSRF: an attacker supplies a URL and the server
     * fetches something only the server can reach.
     *
     * In local development the media origin is genuinely the other storefront on
     * `localhost`, so the check has to be relaxed to see real photography while working.
     * It is gated on NODE_ENV so it cannot reach production, where media is served from a
     * public CDN over HTTPS (ADR-012) and this must stay off. `buildRemotePatterns` still
     * limits fetches to the one configured origin either way.
     */
    dangerouslyAllowLocalIP: process.env.NODE_ENV !== "production",

    /*
     * The shared backend still serves generated SVG placeholders for products without
     * photography. SVG can carry script, so Next refuses it unless this is set; the CSP and
     * `contentDispositionType` are what make it safe.
     *
     * This holds only because every SVG here is generated by us. Customer-uploaded CNIC
     * documents never pass through next/image at all — they are fetched through a signed
     * URL by the reviewer, not rendered as catalog media (ADR-024).
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },

  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          // TRD section 10 security baseline.
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
};

export default config;
