/**
 * Launch catalog — the Phase 0 "20-30 representative products" deliverable.
 *
 * Prices are realistic PKR retail figures for the Pakistani market and are integers: PKR is
 * presented without decimals throughout. Specs are structured values keyed to the attribute
 * schemas, never free text.
 */

export interface CategorySeed {
  handle: string;
  name: string;
  description: string;
  children?: CategorySeed[];
}

export const CATEGORIES: CategorySeed[] = [
  {
    handle: "laptops",
    name: "Laptops",
    description:
      "Ultrabooks, creator laptops and gaming machines with full specifications and local warranty.",
    children: [
      { handle: "ultrabooks", name: "Ultrabooks", description: "Thin and light laptops under 1.5 kg." },
      { handle: "gaming-laptops", name: "Gaming laptops", description: "Discrete graphics and high refresh displays." },
    ],
  },
  {
    handle: "smartphones",
    name: "Smartphones",
    description: "PTA status stated on every listing, with exact model and variant identity.",
    children: [
      { handle: "flagship-phones", name: "Flagship phones", description: "Current-generation flagship handsets." },
      { handle: "mid-range-phones", name: "Mid-range phones", description: "Balanced performance and price." },
    ],
  },
  {
    handle: "audio",
    name: "Audio",
    description: "Headphones, earbuds and speakers with measured battery life and codec support.",
    children: [
      { handle: "headphones", name: "Headphones", description: "Over-ear and on-ear headphones." },
      { handle: "earbuds", name: "Earbuds", description: "True wireless and in-ear models." },
    ],
  },
];

export const BRANDS = [
  "Apple",
  "Samsung",
  "Sony",
  "Dell",
  "HP",
  "Lenovo",
  "ASUS",
  "Xiaomi",
  "Google",
  "Bose",
  "JBL",
  "Anker",
] as const;

export interface VariantSeed {
  title: string;
  sku: string;
  price_pkr: number;
  compare_at_pkr?: number;
  inventory: number;
  options: Record<string, string>;
  /** Variant-scoped specs, e.g. ram_gb and storage_gb. */
  specs?: Record<string, string | number | boolean>;
}

export interface ProductSeed {
  handle: string;
  title: string;
  subtitle: string;
  brand: string;
  model: string;
  category: string;
  parentCategory: "laptops" | "smartphones" | "audio";
  warranty: string;
  description: string;
  /** Product-level specs shared by every variant. */
  specs: Record<string, string | number | boolean | string[]>;
  boxContents: string[];
  optionName: string;
  variants: VariantSeed[];
  weightGrams: number;
}

export const PRODUCTS: ProductSeed[] = [
  // ---------------------------------------------------------------- Laptops
  {
    handle: "macbook-air-15-m3",
    title: "Apple MacBook Air 15-inch (M3)",
    subtitle: "Fanless 15-inch ultrabook with an 18-hour battery",
    brand: "Apple",
    model: "MacBook Air 15 M3",
    category: "ultrabooks",
    parentCategory: "laptops",
    warranty: "manufacturer-1y",
    description:
      "A 15-inch fanless laptop built around the M3 chip. It stays silent under sustained load and runs a full working day away from a charger, which makes it a practical choice where power cuts are routine.",
    specs: {
      processor: "Apple M3 (8-core CPU)",
      gpu: "Apple M3 10-core GPU",
      screen_size_in: 15.3,
      panel_type: "ips_lcd",
      resolution: "2880 x 1864",
      refresh_rate_hz: 60,
      battery_wh: 66.5,
      storage_type: "nvme_ssd",
      connectivity: ["wifi_6e", "bluetooth_5_3"],
      ports: "2x Thunderbolt/USB 4, MagSafe 3, 3.5 mm headphone",
      usb_c_ports: 2,
      weight_g: 1510,
      release_year: 2024,
    },
    boxContents: ["MacBook Air 15-inch", "35W dual USB-C power adapter", "USB-C to MagSafe 3 cable"],
    optionName: "Configuration",
    weightGrams: 1510,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "APL-MBA15M3-8-256",
        price_pkr: 384999,
        inventory: 12,
        options: { Configuration: "8GB / 256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
      {
        title: "16GB / 512GB",
        sku: "APL-MBA15M3-16-512",
        price_pkr: 469999,
        compare_at_pkr: 489999,
        inventory: 7,
        options: { Configuration: "16GB / 512GB" },
        specs: { ram_gb: 16, storage_gb: 512 },
      },
    ],
  },
  {
    handle: "dell-xps-13-9340",
    title: "Dell XPS 13 9340",
    subtitle: "13.4-inch OLED ultrabook with Intel Core Ultra 7",
    brand: "Dell",
    model: "XPS 13 9340",
    category: "ultrabooks",
    parentCategory: "laptops",
    warranty: "distributor-1y",
    description:
      "A compact 13.4-inch ultrabook with an OLED panel and Core Ultra 7 processor. Suited to office and development work where portability matters more than sustained graphics performance.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      gpu: "Intel Arc integrated graphics",
      screen_size_in: 13.4,
      panel_type: "oled",
      resolution: "2880 x 1800",
      refresh_rate_hz: 60,
      battery_wh: 55,
      storage_type: "nvme_ssd",
      connectivity: ["wifi_6e", "bluetooth_5_3"],
      ports: "2x Thunderbolt 4",
      usb_c_ports: 2,
      weight_g: 1190,
      release_year: 2024,
    },
    boxContents: ["XPS 13 laptop", "60W USB-C adapter", "USB-C to USB-A adapter"],
    optionName: "Configuration",
    weightGrams: 1190,
    variants: [
      {
        title: "16GB / 512GB",
        sku: "DEL-XPS13-16-512",
        price_pkr: 429999,
        inventory: 5,
        options: { Configuration: "16GB / 512GB" },
        specs: { ram_gb: 16, storage_gb: 512 },
      },
      {
        title: "32GB / 1TB",
        sku: "DEL-XPS13-32-1024",
        price_pkr: 549999,
        inventory: 3,
        options: { Configuration: "32GB / 1TB" },
        specs: { ram_gb: 32, storage_gb: 1024 },
      },
    ],
  },
  {
    handle: "asus-rog-zephyrus-g14",
    title: "ASUS ROG Zephyrus G14 (2024)",
    subtitle: "14-inch OLED gaming laptop with RTX 4060",
    brand: "ASUS",
    model: "GA403UV",
    category: "gaming-laptops",
    parentCategory: "laptops",
    warranty: "distributor-1y",
    description:
      "A 14-inch gaming laptop with a 120 Hz OLED display and an RTX 4060. Compact enough to carry daily while still handling current titles at 1600p.",
    specs: {
      processor: "AMD Ryzen 9 8945HS",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      screen_size_in: 14,
      panel_type: "oled",
      resolution: "2880 x 1800",
      refresh_rate_hz: 120,
      battery_wh: 73,
      storage_type: "nvme_ssd",
      connectivity: ["wifi_6e", "bluetooth_5_3"],
      ports: "1x USB-C 4, 1x USB-C 3.2, 2x USB-A, HDMI 2.1, microSD",
      usb_c_ports: 2,
      weight_g: 1500,
      release_year: 2024,
    },
    boxContents: ["ROG Zephyrus G14", "180W power adapter", "Quick start guide"],
    optionName: "Configuration",
    weightGrams: 1500,
    variants: [
      {
        title: "16GB / 1TB",
        sku: "ASU-G14-16-1024",
        price_pkr: 579999,
        compare_at_pkr: 619999,
        inventory: 4,
        options: { Configuration: "16GB / 1TB" },
        specs: { ram_gb: 16, storage_gb: 1024 },
      },
      {
        title: "32GB / 1TB",
        sku: "ASU-G14-32-1024",
        price_pkr: 664999,
        inventory: 2,
        options: { Configuration: "32GB / 1TB" },
        specs: { ram_gb: 32, storage_gb: 1024 },
      },
    ],
  },
  {
    handle: "lenovo-thinkpad-x1-carbon-g12",
    title: "Lenovo ThinkPad X1 Carbon Gen 12",
    subtitle: "14-inch business ultrabook, 1.09 kg",
    brand: "Lenovo",
    model: "X1 Carbon Gen 12",
    category: "ultrabooks",
    parentCategory: "laptops",
    warranty: "manufacturer-2y",
    description:
      "A 1.09 kg business laptop with a full port selection and a two-year manufacturer warranty. Built for people who travel with their machine every day.",
    specs: {
      processor: "Intel Core Ultra 7 155U",
      gpu: "Intel Graphics",
      screen_size_in: 14,
      panel_type: "ips_lcd",
      resolution: "1920 x 1200",
      refresh_rate_hz: 60,
      battery_wh: 57,
      storage_type: "nvme_ssd",
      connectivity: ["wifi_6e", "bluetooth_5_3"],
      ports: "2x Thunderbolt 4, 2x USB-A, HDMI 2.1",
      usb_c_ports: 2,
      weight_g: 1090,
      release_year: 2024,
    },
    boxContents: ["ThinkPad X1 Carbon", "65W USB-C adapter"],
    optionName: "Configuration",
    weightGrams: 1090,
    variants: [
      {
        title: "16GB / 512GB",
        sku: "LEN-X1C12-16-512",
        price_pkr: 519999,
        inventory: 6,
        options: { Configuration: "16GB / 512GB" },
        specs: { ram_gb: 16, storage_gb: 512 },
      },
    ],
  },
  {
    handle: "hp-pavilion-plus-14",
    title: "HP Pavilion Plus 14",
    subtitle: "14-inch 2.8K OLED for everyday work",
    brand: "HP",
    model: "Pavilion Plus 14-ew1",
    category: "ultrabooks",
    parentCategory: "laptops",
    warranty: "shop-6m",
    description:
      "A mid-range 14-inch laptop with a 2.8K OLED panel. A sensible choice for study and office work where the display matters more than graphics power.",
    specs: {
      processor: "Intel Core i5-1335U",
      gpu: "Intel Iris Xe",
      screen_size_in: 14,
      panel_type: "oled",
      resolution: "2880 x 1800",
      refresh_rate_hz: 90,
      battery_wh: 51,
      storage_type: "nvme_ssd",
      connectivity: ["wifi_6", "bluetooth_5_3"],
      ports: "1x USB-C, 2x USB-A, HDMI 2.1",
      usb_c_ports: 1,
      weight_g: 1400,
      release_year: 2024,
    },
    boxContents: ["Pavilion Plus 14", "65W adapter"],
    optionName: "Configuration",
    weightGrams: 1400,
    variants: [
      {
        title: "16GB / 512GB",
        sku: "HP-PAV14-16-512",
        price_pkr: 264999,
        compare_at_pkr: 284999,
        inventory: 9,
        options: { Configuration: "16GB / 512GB" },
        specs: { ram_gb: 16, storage_gb: 512 },
      },
    ],
  },

  // ------------------------------------------------------------ Smartphones
  {
    handle: "samsung-galaxy-s24-ultra",
    title: "Samsung Galaxy S24 Ultra",
    subtitle: "6.8-inch flagship with a titanium frame and S Pen",
    brand: "Samsung",
    model: "SM-S928B",
    category: "flagship-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "Samsung's flagship handset with a 200 MP main camera and a built-in S Pen. Supplied PTA approved, so it works on local networks without a separate registration fee.",
    specs: {
      pta_status: "approved",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      screen_size_in: 6.8,
      panel_type: "amoled",
      resolution: "3120 x 1440",
      refresh_rate_hz: 120,
      main_camera_mp: 200,
      front_camera_mp: 12,
      video_recording: "8K at 30fps, 4K at 60fps",
      battery_mah: 5000,
      fast_charging_w: 45,
      connectivity: ["5g", "wifi_7", "bluetooth_5_3", "nfc"],
      water_resistance: "ip68",
      weight_g: 232,
      release_year: 2024,
    },
    boxContents: ["Galaxy S24 Ultra", "USB-C to USB-C cable", "SIM ejector tool"],
    optionName: "Storage",
    weightGrams: 232,
    variants: [
      {
        title: "12GB / 256GB",
        sku: "SAM-S24U-12-256",
        price_pkr: 424999,
        inventory: 8,
        options: { Storage: "256GB" },
        specs: { ram_gb: 12, storage_gb: 256 },
      },
      {
        title: "12GB / 512GB",
        sku: "SAM-S24U-12-512",
        price_pkr: 469999,
        compare_at_pkr: 489999,
        inventory: 4,
        options: { Storage: "512GB" },
        specs: { ram_gb: 12, storage_gb: 512 },
      },
    ],
  },
  {
    handle: "apple-iphone-15-pro",
    title: "Apple iPhone 15 Pro",
    subtitle: "6.1-inch titanium flagship with USB-C",
    brand: "Apple",
    model: "A3102",
    category: "flagship-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "The 6.1-inch iPhone 15 Pro with a titanium frame, A17 Pro chip and USB-C. Supplied PTA approved for use on Pakistani networks.",
    specs: {
      pta_status: "approved",
      processor: "Apple A17 Pro",
      screen_size_in: 6.1,
      panel_type: "oled",
      resolution: "2556 x 1179",
      refresh_rate_hz: 120,
      main_camera_mp: 48,
      front_camera_mp: 12,
      video_recording: "4K ProRes at 60fps",
      battery_mah: 3274,
      fast_charging_w: 20,
      connectivity: ["5g", "wifi_6e", "bluetooth_5_3", "nfc"],
      water_resistance: "ip68",
      weight_g: 187,
      release_year: 2023,
    },
    boxContents: ["iPhone 15 Pro", "USB-C charge cable", "Documentation"],
    optionName: "Storage",
    weightGrams: 187,
    variants: [
      {
        title: "128GB",
        sku: "APL-IP15P-128",
        price_pkr: 419999,
        inventory: 6,
        options: { Storage: "128GB" },
        specs: { ram_gb: 8, storage_gb: 128 },
      },
      {
        title: "256GB",
        sku: "APL-IP15P-256",
        price_pkr: 459999,
        inventory: 5,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
      {
        title: "512GB",
        sku: "APL-IP15P-512",
        price_pkr: 539999,
        inventory: 2,
        options: { Storage: "512GB" },
        specs: { ram_gb: 8, storage_gb: 512 },
      },
    ],
  },
  {
    handle: "google-pixel-8",
    title: "Google Pixel 8",
    subtitle: "6.2-inch Android with seven years of updates",
    brand: "Google",
    model: "GKWS6",
    category: "flagship-phones",
    parentCategory: "smartphones",
    warranty: "shop-6m",
    description:
      "A compact 6.2-inch Android phone with a strong camera and a seven-year update commitment. This unit is not PTA approved — registration is the buyer's responsibility and adds a separate government fee.",
    specs: {
      // Stated plainly rather than hidden. UX spec section 1: reduce uncertainty before commit.
      pta_status: "not_approved",
      processor: "Google Tensor G3",
      screen_size_in: 6.2,
      panel_type: "oled",
      resolution: "2400 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 10,
      video_recording: "4K at 60fps",
      battery_mah: 4575,
      fast_charging_w: 27,
      connectivity: ["5g", "wifi_7", "bluetooth_5_3", "nfc"],
      water_resistance: "ip68",
      weight_g: 187,
      release_year: 2023,
    },
    boxContents: ["Pixel 8", "USB-C to USB-C cable", "SIM tool"],
    optionName: "Storage",
    weightGrams: 187,
    variants: [
      {
        title: "128GB",
        sku: "GOO-PX8-128",
        price_pkr: 189999,
        inventory: 7,
        options: { Storage: "128GB" },
        specs: { ram_gb: 8, storage_gb: 128 },
      },
      {
        title: "256GB",
        sku: "GOO-PX8-256",
        price_pkr: 214999,
        inventory: 3,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "xiaomi-redmi-note-13-pro",
    title: "Xiaomi Redmi Note 13 Pro",
    subtitle: "6.67-inch AMOLED with 200 MP camera",
    brand: "Xiaomi",
    model: "2312DRA50G",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "A mid-range handset with a 120 Hz AMOLED display and 67W charging. PTA approved and covered by local distributor warranty.",
    specs: {
      pta_status: "approved",
      processor: "Snapdragon 7s Gen 2",
      screen_size_in: 6.67,
      panel_type: "amoled",
      resolution: "2712 x 1220",
      refresh_rate_hz: 120,
      main_camera_mp: 200,
      front_camera_mp: 16,
      video_recording: "4K at 30fps",
      battery_mah: 5100,
      fast_charging_w: 67,
      connectivity: ["5g", "wifi_6", "bluetooth_5_3", "nfc"],
      water_resistance: "ip54",
      weight_g: 187,
      release_year: 2024,
    },
    boxContents: ["Redmi Note 13 Pro", "67W charger", "USB-C cable", "Protective case"],
    optionName: "Storage",
    weightGrams: 187,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "XIA-RN13P-8-256",
        price_pkr: 84999,
        compare_at_pkr: 92999,
        inventory: 18,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
      {
        title: "12GB / 512GB",
        sku: "XIA-RN13P-12-512",
        price_pkr: 104999,
        inventory: 11,
        options: { Storage: "512GB" },
        specs: { ram_gb: 12, storage_gb: 512 },
      },
    ],
  },
  {
    handle: "samsung-galaxy-a55",
    title: "Samsung Galaxy A55 5G",
    subtitle: "6.6-inch Super AMOLED mid-range",
    brand: "Samsung",
    model: "SM-A556E",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "A mid-range 5G handset with a metal frame and four years of Android updates. PTA approved.",
    specs: {
      pta_status: "approved",
      processor: "Exynos 1480",
      screen_size_in: 6.6,
      panel_type: "amoled",
      resolution: "2340 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 32,
      video_recording: "4K at 30fps",
      battery_mah: 5000,
      fast_charging_w: 25,
      connectivity: ["5g", "wifi_6", "bluetooth_5_3", "nfc"],
      water_resistance: "ip67",
      weight_g: 213,
      release_year: 2024,
    },
    boxContents: ["Galaxy A55", "USB-C cable", "SIM tool"],
    optionName: "Storage",
    weightGrams: 213,
    variants: [
      {
        title: "8GB / 128GB",
        sku: "SAM-A55-8-128",
        price_pkr: 119999,
        inventory: 14,
        options: { Storage: "128GB" },
        specs: { ram_gb: 8, storage_gb: 128 },
      },
      {
        title: "8GB / 256GB",
        sku: "SAM-A55-8-256",
        price_pkr: 134999,
        inventory: 9,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },

  // ------------------------------------------------------------------ Audio
  {
    handle: "sony-wh-1000xm5",
    title: "Sony WH-1000XM5 Wireless Noise-Cancelling Headphones",
    subtitle: "Over-ear ANC with 30-hour battery",
    brand: "Sony",
    model: "WH-1000XM5",
    category: "headphones",
    parentCategory: "audio",
    warranty: "manufacturer-1y",
    description:
      "Over-ear headphones with adaptive noise cancellation and 30 hours of battery with ANC active. The exact-model search case in J1 of the PRD.",
    specs: {
      form_factor: "over_ear",
      anc: true,
      driver_size_mm: 30,
      battery_hours: 30,
      connectivity: ["bluetooth_5_3"],
      water_resistance: "none",
      weight_g: 250,
      release_year: 2022,
    },
    boxContents: ["WH-1000XM5 headphones", "Carrying case", "USB-C cable", "3.5 mm audio cable"],
    optionName: "Colour",
    weightGrams: 250,
    variants: [
      {
        title: "Black",
        sku: "SONY-WH1000XM5-BLK",
        price_pkr: 119999,
        compare_at_pkr: 129999,
        inventory: 15,
        options: { Colour: "Black" },
        specs: { colour: "Black" },
      },
      {
        title: "Silver",
        sku: "SONY-WH1000XM5-SLV",
        price_pkr: 119999,
        inventory: 6,
        options: { Colour: "Silver" },
        specs: { colour: "Silver" },
      },
    ],
  },
  {
    handle: "sony-wh-1000xm6",
    title: "Sony WH-1000XM6 Wireless Noise-Cancelling Headphones",
    subtitle: "Over-ear ANC with 32-hour battery",
    brand: "Sony",
    model: "WH-1000XM6",
    category: "headphones",
    parentCategory: "audio",
    warranty: "manufacturer-1y",
    description:
      "The successor to the XM5, with a revised driver and 32 hours of battery. Listed alongside the XM5 so an exact-model search must distinguish the two.",
    specs: {
      form_factor: "over_ear",
      anc: true,
      driver_size_mm: 30,
      battery_hours: 32,
      connectivity: ["bluetooth_5_4"],
      water_resistance: "none",
      weight_g: 254,
      release_year: 2025,
    },
    boxContents: ["WH-1000XM6 headphones", "Carrying case", "USB-C cable", "3.5 mm audio cable"],
    optionName: "Colour",
    weightGrams: 254,
    variants: [
      {
        title: "Black",
        sku: "SONY-WH1000XM6-BLK",
        price_pkr: 154999,
        inventory: 9,
        options: { Colour: "Black" },
        specs: { colour: "Black" },
      },
      {
        title: "Midnight Blue",
        sku: "SONY-WH1000XM6-BLU",
        price_pkr: 154999,
        inventory: 4,
        options: { Colour: "Midnight Blue" },
        specs: { colour: "Midnight Blue" },
      },
    ],
  },
  {
    handle: "apple-airpods-pro-2",
    title: "Apple AirPods Pro (2nd generation, USB-C)",
    subtitle: "True wireless with adaptive audio",
    brand: "Apple",
    model: "MTJV3",
    category: "earbuds",
    parentCategory: "audio",
    warranty: "manufacturer-1y",
    description:
      "True wireless earbuds with active noise cancellation and a USB-C charging case. Six hours per charge, thirty with the case.",
    specs: {
      form_factor: "true_wireless",
      anc: true,
      driver_size_mm: 11,
      battery_hours: 6,
      connectivity: ["bluetooth_5_3"],
      water_resistance: "ip54",
      weight_g: 61,
      release_year: 2023,
    },
    boxContents: ["AirPods Pro", "MagSafe charging case (USB-C)", "Four sizes of ear tips", "USB-C cable"],
    optionName: "Colour",
    weightGrams: 61,
    variants: [
      {
        title: "White",
        sku: "APL-APP2-USBC-WHT",
        price_pkr: 84999,
        inventory: 20,
        options: { Colour: "White" },
        specs: { colour: "White" },
      },
    ],
  },
  {
    handle: "bose-quietcomfort-ultra",
    title: "Bose QuietComfort Ultra Headphones",
    subtitle: "Over-ear ANC with spatial audio",
    brand: "Bose",
    model: "QC Ultra",
    category: "headphones",
    parentCategory: "audio",
    warranty: "distributor-1y",
    description:
      "Over-ear headphones focused on noise cancellation and comfort for long sessions, with 24 hours of battery.",
    specs: {
      form_factor: "over_ear",
      anc: true,
      driver_size_mm: 35,
      battery_hours: 24,
      connectivity: ["bluetooth_5_3"],
      water_resistance: "none",
      weight_g: 254,
      release_year: 2023,
    },
    boxContents: ["QuietComfort Ultra headphones", "Carrying case", "USB-C cable", "2.5 mm to 3.5 mm cable"],
    optionName: "Colour",
    weightGrams: 254,
    variants: [
      {
        title: "Black",
        sku: "BOS-QCU-BLK",
        price_pkr: 139999,
        inventory: 5,
        options: { Colour: "Black" },
        specs: { colour: "Black" },
      },
      {
        title: "White Smoke",
        sku: "BOS-QCU-WHT",
        price_pkr: 139999,
        compare_at_pkr: 149999,
        inventory: 3,
        options: { Colour: "White Smoke" },
        specs: { colour: "White Smoke" },
      },
    ],
  },
  {
    handle: "samsung-galaxy-buds3-pro",
    title: "Samsung Galaxy Buds3 Pro",
    subtitle: "True wireless with 24-bit audio",
    brand: "Samsung",
    model: "SM-R630",
    category: "earbuds",
    parentCategory: "audio",
    warranty: "manufacturer-1y",
    description: "True wireless earbuds with adaptive ANC and 24-bit playback on supported devices.",
    specs: {
      form_factor: "true_wireless",
      anc: true,
      driver_size_mm: 10,
      battery_hours: 6,
      connectivity: ["bluetooth_5_4"],
      water_resistance: "ip57",
      weight_g: 54,
      release_year: 2024,
    },
    boxContents: ["Galaxy Buds3 Pro", "Charging case", "Ear tips", "USB-C cable"],
    optionName: "Colour",
    weightGrams: 54,
    variants: [
      {
        title: "Silver",
        sku: "SAM-BUDS3P-SLV",
        price_pkr: 64999,
        inventory: 12,
        options: { Colour: "Silver" },
        specs: { colour: "Silver" },
      },
    ],
  },
  {
    handle: "jbl-tune-770nc",
    title: "JBL Tune 770NC",
    subtitle: "Over-ear ANC with 70-hour battery",
    brand: "JBL",
    model: "Tune 770NC",
    category: "headphones",
    parentCategory: "audio",
    warranty: "shop-6m",
    description:
      "Budget over-ear headphones with adaptive noise cancelling and an unusually long 70-hour battery with ANC off.",
    specs: {
      form_factor: "over_ear",
      anc: true,
      driver_size_mm: 40,
      battery_hours: 70,
      connectivity: ["bluetooth_5_3"],
      water_resistance: "none",
      weight_g: 220,
      release_year: 2023,
    },
    boxContents: ["Tune 770NC headphones", "USB-C cable", "3.5 mm cable"],
    optionName: "Colour",
    weightGrams: 220,
    variants: [
      {
        title: "Black",
        sku: "JBL-T770NC-BLK",
        price_pkr: 27999,
        compare_at_pkr: 32999,
        inventory: 25,
        options: { Colour: "Black" },
        specs: { colour: "Black" },
      },
      {
        title: "Blue",
        sku: "JBL-T770NC-BLU",
        price_pkr: 27999,
        inventory: 14,
        options: { Colour: "Blue" },
        specs: { colour: "Blue" },
      },
    ],
  },
  {
    handle: "anker-soundcore-space-one",
    title: "Anker Soundcore Space One",
    subtitle: "Over-ear ANC under Rs 25,000",
    brand: "Anker",
    model: "A3116",
    category: "headphones",
    parentCategory: "audio",
    warranty: "shop-6m",
    description:
      "Entry-level over-ear headphones with active noise cancellation and 40 hours of battery with ANC active.",
    specs: {
      form_factor: "over_ear",
      anc: true,
      driver_size_mm: 40,
      battery_hours: 40,
      connectivity: ["bluetooth_5_3"],
      water_resistance: "none",
      weight_g: 265,
      release_year: 2023,
    },
    boxContents: ["Space One headphones", "Carrying pouch", "USB-C cable", "3.5 mm cable"],
    optionName: "Colour",
    weightGrams: 265,
    variants: [
      {
        title: "Jet Black",
        sku: "ANK-SPACEONE-BLK",
        price_pkr: 22999,
        inventory: 30,
        options: { Colour: "Jet Black" },
        specs: { colour: "Jet Black" },
      },
      {
        title: "Latte Cream",
        sku: "ANK-SPACEONE-CRM",
        price_pkr: 22999,
        inventory: 16,
        options: { Colour: "Latte Cream" },
        specs: { colour: "Latte Cream" },
      },
    ],
  },
];
