import type { ProductSeed } from "./catalog";

/**
 * The FONEKIST phone catalogue.
 *
 * These are the products the phone-only sales channel carries, on top of the handful of
 * phones already in the shared launch catalogue. Twenty-plus handsets across the brands
 * that actually sell in Pakistan, including the sub-brands that exist to prove brand
 * canonicalisation works: Redmi and POCO are Xiaomi products and must land on the Xiaomi
 * brand page, while Tecno and Infinix stay separate because a customer shopping for one
 * does not consider the other a substitute.
 *
 * PTA status is stated on every one, because selling an unregistered handset without saying
 * so is exactly the purchase uncertainty this storefront exists to remove. Where a handset
 * is genuinely sold unregistered it says `not_approved`, and the storefront says so loudly
 * rather than leaving it blank.
 *
 * Prices are plausible PKR retail figures for seeding, in whole rupees. They are seed data,
 * not a price list: a launch catalogue has to be verified against real supplier pricing
 * (Workstream 7), and the photography is still stand-in.
 */
export const PHONES: ProductSeed[] = [
  /* ------------------------------------------------------------------ Samsung */
  {
    handle: "samsung-galaxy-s24",
    title: "Samsung Galaxy S24",
    subtitle: "6.2-inch compact flagship",
    brand: "Samsung",
    model: "SM-S921B",
    category: "flagship-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "The compact Galaxy flagship. A 6.2-inch 120 Hz display and a flat frame make it one of the few current handsets that is genuinely usable one-handed.",
    specs: {
      pta_status: "approved",
      processor: "Exynos 2400",
      screen_size_in: 6.2,
      panel_type: "amoled",
      resolution: "2340 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 12,
      video_recording: "8K at 30fps",
      battery_mah: 4000,
      fast_charging_w: 25,
      connectivity: ["5g", "wifi_6e", "bluetooth_5_3", "nfc"],
      water_resistance: "ip68",
      weight_g: 167,
      release_year: 2024,
    },
    boxContents: ["Galaxy S24", "USB-C to USB-C cable", "SIM ejector tool"],
    optionName: "Storage",
    weightGrams: 167,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "SAM-S24-8-256",
        price_pkr: 249999,
        inventory: 10,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "samsung-galaxy-a35",
    title: "Samsung Galaxy A35 5G",
    subtitle: "6.6-inch mid-range with an IP67 rating",
    brand: "Samsung",
    model: "SM-A356E",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "A mid-range Galaxy with a proper water resistance rating and four years of software updates, which is unusual at this price.",
    specs: {
      pta_status: "approved",
      processor: "Exynos 1380",
      screen_size_in: 6.6,
      panel_type: "amoled",
      resolution: "2340 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 13,
      video_recording: "4K at 30fps",
      battery_mah: 5000,
      fast_charging_w: 25,
      connectivity: ["5g", "wifi_6", "bluetooth_5_3", "nfc"],
      water_resistance: "ip67",
      weight_g: 209,
      release_year: 2024,
    },
    boxContents: ["Galaxy A35 5G", "USB-C cable", "SIM ejector tool"],
    optionName: "Storage",
    weightGrams: 209,
    variants: [
      {
        title: "8GB / 128GB",
        sku: "SAM-A35-8-128",
        price_pkr: 114999,
        inventory: 20,
        options: { Storage: "128GB" },
        specs: { ram_gb: 8, storage_gb: 128 },
      },
      {
        title: "8GB / 256GB",
        sku: "SAM-A35-8-256",
        price_pkr: 129999,
        inventory: 12,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "samsung-galaxy-a15",
    title: "Samsung Galaxy A15",
    subtitle: "6.5-inch entry handset with a 5000 mAh battery",
    brand: "Samsung",
    model: "SM-A155F",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "An entry-level Galaxy with an AMOLED panel and a battery that lasts a working day of heavy use, which matters where charging is not always available.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Helio G99",
      screen_size_in: 6.5,
      panel_type: "amoled",
      resolution: "2340 x 1080",
      refresh_rate_hz: 90,
      main_camera_mp: 50,
      front_camera_mp: 13,
      video_recording: "1080p at 30fps",
      battery_mah: 5000,
      fast_charging_w: 25,
      connectivity: ["bluetooth_5_3", "nfc"],
      weight_g: 200,
      release_year: 2024,
    },
    boxContents: ["Galaxy A15", "USB-C cable", "SIM ejector tool"],
    optionName: "Storage",
    weightGrams: 200,
    variants: [
      {
        title: "6GB / 128GB",
        sku: "SAM-A15-6-128",
        price_pkr: 64999,
        inventory: 30,
        options: { Storage: "128GB" },
        specs: { ram_gb: 6, storage_gb: 128 },
      },
    ],
  },

  /* -------------------------------------------------------------------- Apple */
  {
    handle: "apple-iphone-15",
    title: "Apple iPhone 15",
    subtitle: "6.1-inch with USB-C and Dynamic Island",
    brand: "Apple",
    model: "A3090",
    category: "flagship-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "The standard iPhone 15 with USB-C and a 48 MP main camera. Supplied PTA approved for use on Pakistani networks.",
    specs: {
      pta_status: "approved",
      processor: "Apple A16 Bionic",
      screen_size_in: 6.1,
      panel_type: "oled",
      resolution: "2556 x 1179",
      refresh_rate_hz: 60,
      main_camera_mp: 48,
      front_camera_mp: 12,
      video_recording: "4K at 60fps",
      battery_mah: 3349,
      fast_charging_w: 20,
      connectivity: ["5g", "wifi_6", "bluetooth_5_3", "nfc"],
      water_resistance: "ip68",
      weight_g: 171,
      release_year: 2023,
    },
    boxContents: ["iPhone 15", "USB-C charge cable", "Documentation"],
    optionName: "Storage",
    weightGrams: 171,
    variants: [
      {
        title: "128GB",
        sku: "APL-IP15-128",
        price_pkr: 289999,
        inventory: 9,
        options: { Storage: "128GB" },
        specs: { storage_gb: 128, ram_gb: 6 },
      },
      {
        title: "256GB",
        sku: "APL-IP15-256",
        price_pkr: 324999,
        inventory: 6,
        options: { Storage: "256GB" },
        specs: { storage_gb: 256, ram_gb: 6 },
      },
    ],
  },
  {
    handle: "apple-iphone-13",
    title: "Apple iPhone 13",
    subtitle: "6.1-inch, still current, still supported",
    brand: "Apple",
    model: "A2633",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "manufacturer-1y",
    description:
      "The iPhone 13 remains on current software and is the least expensive way into an iPhone that will keep receiving updates for years.",
    specs: {
      pta_status: "approved",
      processor: "Apple A15 Bionic",
      screen_size_in: 6.1,
      panel_type: "oled",
      resolution: "2532 x 1170",
      refresh_rate_hz: 60,
      main_camera_mp: 12,
      front_camera_mp: 12,
      video_recording: "4K at 60fps",
      battery_mah: 3240,
      fast_charging_w: 20,
      connectivity: ["5g", "wifi_6", "bluetooth_5_0", "nfc"],
      water_resistance: "ip68",
      weight_g: 174,
      release_year: 2021,
    },
    boxContents: ["iPhone 13", "USB-C to Lightning cable", "Documentation"],
    optionName: "Storage",
    weightGrams: 174,
    variants: [
      {
        title: "128GB",
        sku: "APL-IP13-128",
        price_pkr: 199999,
        inventory: 7,
        options: { Storage: "128GB" },
        specs: { storage_gb: 128, ram_gb: 4 },
      },
    ],
  },

  /* ---------------------------------- Xiaomi, and its Redmi and POCO sub-brands */
  {
    handle: "xiaomi-14t-pro",
    title: "Xiaomi 14T Pro",
    subtitle: "6.67-inch with a Leica-tuned camera",
    brand: "Xiaomi",
    model: "2407FRK8EG",
    category: "flagship-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "A near-flagship with a Leica-tuned 50 MP main camera and 120 W charging, which fills a dead battery in about twenty minutes.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Dimensity 9300+",
      screen_size_in: 6.67,
      panel_type: "amoled",
      resolution: "2712 x 1220",
      refresh_rate_hz: 144,
      main_camera_mp: 50,
      front_camera_mp: 32,
      video_recording: "8K at 24fps",
      battery_mah: 5000,
      fast_charging_w: 120,
      connectivity: ["5g", "wifi_7", "bluetooth_5_4", "nfc"],
      water_resistance: "ip68",
      weight_g: 209,
      release_year: 2024,
    },
    boxContents: ["Xiaomi 14T Pro", "120W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 209,
    variants: [
      {
        title: "12GB / 512GB",
        sku: "XIA-14TP-12-512",
        price_pkr: 219999,
        inventory: 8,
        options: { Storage: "512GB" },
        specs: { ram_gb: 12, storage_gb: 512 },
      },
    ],
  },
  {
    handle: "redmi-note-14-pro-plus",
    title: "Redmi Note 14 Pro+ 5G",
    subtitle: "6.67-inch with a 200 MP camera",
    brand: "Redmi",
    model: "24101RN45G",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "The Note that most people actually buy: a 200 MP main camera, 90 W charging and an IP68 rating at a mid-range price.",
    specs: {
      pta_status: "approved",
      processor: "Snapdragon 7s Gen 3",
      screen_size_in: 6.67,
      panel_type: "amoled",
      resolution: "2712 x 1220",
      refresh_rate_hz: 120,
      main_camera_mp: 200,
      front_camera_mp: 20,
      video_recording: "4K at 30fps",
      battery_mah: 5110,
      fast_charging_w: 90,
      connectivity: ["5g", "wifi_6", "bluetooth_5_4", "nfc"],
      water_resistance: "ip68",
      weight_g: 205,
      release_year: 2024,
    },
    boxContents: ["Redmi Note 14 Pro+", "90W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 205,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "RED-N14PP-8-256",
        price_pkr: 124999,
        inventory: 18,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
      {
        title: "12GB / 512GB",
        sku: "RED-N14PP-12-512",
        price_pkr: 144999,
        inventory: 9,
        options: { Storage: "512GB" },
        specs: { ram_gb: 12, storage_gb: 512 },
      },
    ],
  },
  {
    handle: "redmi-13c",
    title: "Redmi 13C",
    subtitle: "6.74-inch budget handset",
    brand: "Redmi",
    model: "23108RN04Y",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "A budget handset with a large display and a 5000 mAh battery. No 5G and an LCD panel, both of which the specification below states plainly.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Helio G85",
      screen_size_in: 6.74,
      panel_type: "ips_lcd",
      resolution: "1600 x 720",
      refresh_rate_hz: 90,
      main_camera_mp: 50,
      front_camera_mp: 8,
      video_recording: "1080p at 30fps",
      battery_mah: 5000,
      fast_charging_w: 18,
      connectivity: ["bluetooth_5_3"],
      weight_g: 192,
      release_year: 2023,
    },
    boxContents: ["Redmi 13C", "Charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 192,
    variants: [
      {
        title: "4GB / 128GB",
        sku: "RED-13C-4-128",
        price_pkr: 37999,
        inventory: 40,
        options: { Storage: "128GB" },
        specs: { ram_gb: 4, storage_gb: 128 },
      },
    ],
  },
  {
    handle: "poco-x6-pro",
    title: "POCO X6 Pro 5G",
    subtitle: "6.67-inch with a Dimensity 8300 Ultra",
    brand: "POCO",
    model: "23122PCD1G",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "The fastest chip you can get at this price, aimed squarely at gaming. It runs warm under sustained load, which is the trade for the performance.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Dimensity 8300 Ultra",
      screen_size_in: 6.67,
      panel_type: "amoled",
      resolution: "2712 x 1220",
      refresh_rate_hz: 120,
      main_camera_mp: 64,
      front_camera_mp: 16,
      video_recording: "4K at 30fps",
      battery_mah: 5000,
      fast_charging_w: 67,
      connectivity: ["5g", "wifi_6", "bluetooth_5_4", "nfc"],
      water_resistance: "ip54",
      weight_g: 186,
      release_year: 2024,
    },
    boxContents: ["POCO X6 Pro", "67W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 186,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "POC-X6P-8-256",
        price_pkr: 109999,
        inventory: 14,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },

  /* --------------------------------------------------------------------- Infinix */
  {
    handle: "infinix-note-40-pro",
    title: "Infinix Note 40 Pro",
    subtitle: "6.78-inch with 45 W wireless charging",
    brand: "Infinix",
    model: "X6850",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "One of the few handsets at this price with wireless charging, and a curved AMOLED panel that would have been flagship-only two years ago.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Helio G99 Ultimate",
      screen_size_in: 6.78,
      panel_type: "amoled",
      resolution: "2436 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 108,
      front_camera_mp: 32,
      video_recording: "4K at 30fps",
      battery_mah: 5000,
      fast_charging_w: 70,
      connectivity: ["bluetooth_5_4", "nfc"],
      weight_g: 195,
      release_year: 2024,
    },
    boxContents: ["Note 40 Pro", "70W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 195,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "INF-N40P-8-256",
        price_pkr: 69999,
        inventory: 25,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "infinix-hot-50-pro",
    title: "Infinix Hot 50 Pro+",
    subtitle: "6.78-inch, 5.9 mm thin",
    brand: "Infinix",
    model: "X6881",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "Unusually thin for a budget handset, with an AMOLED panel. The chip is entry level and the specification says so rather than implying otherwise.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Helio G100",
      screen_size_in: 6.78,
      panel_type: "amoled",
      resolution: "2436 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 8,
      video_recording: "1440p at 30fps",
      battery_mah: 5000,
      fast_charging_w: 33,
      connectivity: ["bluetooth_5_4"],
      weight_g: 162,
      release_year: 2024,
    },
    boxContents: ["Hot 50 Pro+", "33W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 162,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "INF-H50PP-8-256",
        price_pkr: 46999,
        inventory: 35,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },

  /* ----------------------------------------------------------------------- Tecno */
  {
    handle: "tecno-camon-30",
    title: "Tecno Camon 30 5G",
    subtitle: "6.78-inch with a 50 MP front camera",
    brand: "Tecno",
    model: "CL7",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "Built around its cameras, including a 50 MP front sensor. A sensible choice if most of what you shoot is people.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Dimensity 6080",
      screen_size_in: 6.78,
      panel_type: "amoled",
      resolution: "2436 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 50,
      video_recording: "4K at 30fps",
      battery_mah: 5000,
      fast_charging_w: 70,
      connectivity: ["5g", "bluetooth_5_2", "nfc"],
      water_resistance: "ip54",
      weight_g: 187,
      release_year: 2024,
    },
    boxContents: ["Camon 30 5G", "70W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 187,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "TEC-C30-8-256",
        price_pkr: 74999,
        inventory: 22,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "tecno-spark-20-pro",
    title: "Tecno Spark 20 Pro+",
    subtitle: "6.78-inch curved display on a budget",
    brand: "Tecno",
    model: "KJ7",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "A curved AMOLED panel at a price where flat LCDs are the norm. No 5G, which the connectivity list states.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Helio G99 Ultimate",
      screen_size_in: 6.78,
      panel_type: "amoled",
      resolution: "2436 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 108,
      front_camera_mp: 32,
      video_recording: "1440p at 30fps",
      battery_mah: 5000,
      fast_charging_w: 33,
      connectivity: ["bluetooth_5_3"],
      weight_g: 179,
      release_year: 2024,
    },
    boxContents: ["Spark 20 Pro+", "33W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 179,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "TEC-S20PP-8-256",
        price_pkr: 52999,
        inventory: 28,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },

  /* ------------------------------------------------------------------------ vivo */
  {
    handle: "vivo-v40",
    title: "vivo V40 5G",
    subtitle: "6.78-inch with ZEISS optics",
    brand: "vivo",
    model: "V2404",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "ZEISS-tuned cameras and a 5500 mAh battery in a body that stays under 8 mm. Strong on portraits in poor light.",
    specs: {
      pta_status: "approved",
      processor: "Snapdragon 7 Gen 3",
      screen_size_in: 6.78,
      panel_type: "amoled",
      resolution: "2800 x 1260",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 50,
      video_recording: "4K at 60fps",
      battery_mah: 5500,
      fast_charging_w: 80,
      connectivity: ["5g", "wifi_6", "bluetooth_5_4", "nfc"],
      water_resistance: "ip68",
      weight_g: 190,
      release_year: 2024,
    },
    boxContents: ["vivo V40", "80W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 190,
    variants: [
      {
        title: "12GB / 256GB",
        sku: "VIV-V40-12-256",
        price_pkr: 154999,
        inventory: 11,
        options: { Storage: "256GB" },
        specs: { ram_gb: 12, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "vivo-y28",
    title: "vivo Y28 5G",
    subtitle: "6.56-inch entry 5G handset",
    brand: "vivo",
    model: "V2350",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "One of the least expensive 5G handsets sold with PTA approval. An LCD panel and a modest camera are the trade.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Dimensity 6020",
      screen_size_in: 6.56,
      panel_type: "ips_lcd",
      resolution: "1612 x 720",
      refresh_rate_hz: 90,
      main_camera_mp: 50,
      front_camera_mp: 8,
      video_recording: "1080p at 30fps",
      battery_mah: 5000,
      fast_charging_w: 15,
      connectivity: ["5g", "bluetooth_5_1"],
      water_resistance: "ip54",
      weight_g: 199,
      release_year: 2024,
    },
    boxContents: ["vivo Y28 5G", "Charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 199,
    variants: [
      {
        title: "6GB / 128GB",
        sku: "VIV-Y28-6-128",
        price_pkr: 48999,
        inventory: 30,
        options: { Storage: "128GB" },
        specs: { ram_gb: 6, storage_gb: 128 },
      },
    ],
  },

  /* ------------------------------------------------------------------------ OPPO */
  {
    handle: "oppo-reno12",
    title: "OPPO Reno12 5G",
    subtitle: "6.7-inch with a quad-curved display",
    brand: "OPPO",
    model: "CPH2625",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "A well-built mid-range handset with an IP65 rating and 80 W charging. The display curves on all four sides, which some people dislike.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Dimensity 7300",
      screen_size_in: 6.7,
      panel_type: "amoled",
      resolution: "2412 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 32,
      video_recording: "4K at 30fps",
      battery_mah: 5000,
      fast_charging_w: 80,
      connectivity: ["5g", "wifi_6", "bluetooth_5_4", "nfc"],
      water_resistance: "ip55",
      weight_g: 177,
      release_year: 2024,
    },
    boxContents: ["Reno12", "80W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 177,
    variants: [
      {
        title: "12GB / 256GB",
        sku: "OPP-R12-12-256",
        price_pkr: 139999,
        inventory: 13,
        options: { Storage: "256GB" },
        specs: { ram_gb: 12, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "oppo-a3-pro",
    title: "OPPO A3 Pro 5G",
    subtitle: "6.7-inch with an IP69 rating",
    brand: "OPPO",
    model: "CPH2639",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "Rated IP69, which means it survives a high-pressure hose, not just rain. Unusual and genuinely useful in monsoon season.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Dimensity 6300",
      screen_size_in: 6.7,
      panel_type: "amoled",
      resolution: "2412 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 8,
      video_recording: "1080p at 30fps",
      battery_mah: 5100,
      fast_charging_w: 45,
      connectivity: ["5g", "bluetooth_5_3", "nfc"],
      water_resistance: "ip68",
      weight_g: 186,
      release_year: 2024,
    },
    boxContents: ["A3 Pro", "45W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 186,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "OPP-A3P-8-256",
        price_pkr: 84999,
        inventory: 19,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },

  /* ---------------------------------------------------------------------- realme */
  {
    handle: "realme-12-pro-plus",
    title: "realme 12 Pro+ 5G",
    subtitle: "6.7-inch with a periscope telephoto",
    brand: "realme",
    model: "RMX3840",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "A periscope telephoto lens at this price is rare: it gives 3x optical zoom that actually holds detail, rather than a crop of the main sensor.",
    specs: {
      pta_status: "approved",
      processor: "Snapdragon 7s Gen 2",
      screen_size_in: 6.7,
      panel_type: "amoled",
      resolution: "2412 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 32,
      video_recording: "4K at 30fps",
      battery_mah: 5000,
      fast_charging_w: 67,
      connectivity: ["5g", "wifi_6", "bluetooth_5_2", "nfc"],
      water_resistance: "ip65",
      weight_g: 196,
      release_year: 2024,
    },
    boxContents: ["realme 12 Pro+", "67W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 196,
    variants: [
      {
        title: "8GB / 256GB",
        sku: "RLM-12PP-8-256",
        price_pkr: 99999,
        inventory: 16,
        options: { Storage: "256GB" },
        specs: { ram_gb: 8, storage_gb: 256 },
      },
    ],
  },
  {
    handle: "realme-c65",
    title: "realme C65",
    subtitle: "6.67-inch budget handset with 45 W charging",
    brand: "realme",
    model: "RMX3910",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "45 W charging at this price is unusual. The panel is LCD and there is no 5G, both stated in the specification rather than left out.",
    specs: {
      pta_status: "approved",
      processor: "MediaTek Helio G85",
      screen_size_in: 6.67,
      panel_type: "ips_lcd",
      resolution: "1604 x 720",
      refresh_rate_hz: 90,
      main_camera_mp: 50,
      front_camera_mp: 8,
      video_recording: "1080p at 30fps",
      battery_mah: 5000,
      fast_charging_w: 45,
      connectivity: ["bluetooth_5_0"],
      water_resistance: "ip54",
      weight_g: 190,
      release_year: 2024,
    },
    boxContents: ["realme C65", "45W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 190,
    variants: [
      {
        title: "6GB / 128GB",
        sku: "RLM-C65-6-128",
        price_pkr: 42999,
        inventory: 33,
        options: { Storage: "128GB" },
        specs: { ram_gb: 6, storage_gb: 128 },
      },
    ],
  },

  /* --------------------------------------------------------------------- Google */
  {
    handle: "google-pixel-8a",
    title: "Google Pixel 8a",
    subtitle: "6.1-inch with seven years of updates",
    brand: "Google",
    model: "G576D",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "shop-6m",
    description:
      "Seven years of guaranteed software updates, which is the longest support commitment on any handset here. Sold without PTA registration, so the duty is payable separately and the listing says so.",
    specs: {
      // Stated honestly. A handset sold unregistered is usable for a limited period before
      // it is blocked, and a buyer who is not told that will find out the hard way.
      pta_status: "not_approved",
      processor: "Google Tensor G3",
      screen_size_in: 6.1,
      panel_type: "oled",
      resolution: "2400 x 1080",
      refresh_rate_hz: 120,
      main_camera_mp: 64,
      front_camera_mp: 13,
      video_recording: "4K at 60fps",
      battery_mah: 4492,
      fast_charging_w: 18,
      connectivity: ["5g", "wifi_6e", "bluetooth_5_3", "nfc"],
      water_resistance: "ip67",
      weight_g: 188,
      release_year: 2024,
    },
    boxContents: ["Pixel 8a", "USB-C cable", "Quick switch adapter"],
    optionName: "Storage",
    weightGrams: 188,
    variants: [
      {
        title: "8GB / 128GB",
        sku: "GOO-P8A-8-128",
        price_pkr: 139999,
        inventory: 5,
        options: { Storage: "128GB" },
        specs: { ram_gb: 8, storage_gb: 128 },
      },
    ],
  },

  /* -------------------------------------------------------------------- OnePlus */
  {
    handle: "oneplus-nord-4",
    title: "OnePlus Nord 4",
    subtitle: "6.74-inch metal unibody",
    brand: "OnePlus",
    model: "CPH2661",
    category: "mid-range-phones",
    parentCategory: "smartphones",
    warranty: "distributor-1y",
    description:
      "A metal unibody at a mid-range price, which almost nothing else here offers. Fast, cool under load, and light on preinstalled software.",
    specs: {
      pta_status: "approved",
      processor: "Snapdragon 7+ Gen 3",
      screen_size_in: 6.74,
      panel_type: "amoled",
      resolution: "2772 x 1240",
      refresh_rate_hz: 120,
      main_camera_mp: 50,
      front_camera_mp: 16,
      video_recording: "4K at 60fps",
      battery_mah: 5500,
      fast_charging_w: 100,
      connectivity: ["5g", "wifi_6", "bluetooth_5_4", "nfc"],
      water_resistance: "ip65",
      weight_g: 199,
      release_year: 2024,
    },
    boxContents: ["Nord 4", "100W charger", "USB-C cable", "Case"],
    optionName: "Storage",
    weightGrams: 199,
    variants: [
      {
        title: "12GB / 256GB",
        sku: "ONE-N4-12-256",
        price_pkr: 149999,
        inventory: 10,
        options: { Storage: "256GB" },
        specs: { ram_gb: 12, storage_gb: 256 },
      },
    ],
  },
];
