/**
 * The shared contract surface FONEKIST depends on.
 *
 * Everything under this directory except this file and `drift.test.ts` is generated by
 * `pnpm sync:contracts` from `@pk/contracts` in the WEBSITE DESIGN monorepo (ADR-022).
 * Edit those upstream, not here.
 *
 * Import from `@/lib/pk` rather than reaching into the generated subdirectories, so the
 * vendored layout can change without touching call sites.
 */

export * from "./errors/index";
export * from "./envelope/index";
export * from "./states/index";
export * from "./schemas/index";
export * from "./providers/search-provider";
