import { defineRouteConfig } from '@medusajs/admin-sdk';
import { Button,Container,Heading,Text } from '@medusajs/ui';
import { useEffect,useState } from 'react';
type Inquiry={id:string;reference:string;state:'new'|'contacted'|'closed'|'cancelled';created_at:string;advance_pkr:number;discount_pkr:number;coupon_code:string|null;items:{title:string;label:string;total_payable_pkr:number}[];customer?:Record<string,string>|null};
async function api(path:string,body?:unknown){const response=await fetch(path,{credentials:'include',method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error?.message??'Request failed.');return result.data??result;}
export default function InquiriesPage(){
 const [channel,setChannel]=useState(''),[rows,setRows]=useState<Inquiry[]>([]),[selected,setSelected]=useState<Inquiry|null>(null),[count,setCount]=useState(0),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(id:string,start:number){const result=await api(`/admin/inquiries?channel_id=${encodeURIComponent(id)}&offset=${start}`);setRows(result.inquiries);setCount(result.count);setOffset(start);}
 useEffect(()=>{void(async()=>{setBusy(true);try{const data=await api('/admin/sales-channels?limit=100');const c=data.sales_channels.find((c:{name:string})=>c.name.toUpperCase()==='FONEKIST');if(!c)throw new Error('FONEKIST channel not found.');setChannel(c.id);await load(c.id,0);}catch(e){setError((e as Error).message);}finally{setBusy(false);}})();},[]);
 async function open(id:string){setBusy(true);setError('');setSelected(null);try{setSelected((await api('/admin/inquiries/'+encodeURIComponent(id))).inquiry);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Container><Heading>Customer inquiries</Heading><Text className="mt-2">An inquiry is a request to be contacted. It has not created an order, reserved inventory or approved credit.</Text>{error&&<Text className="mt-3 text-ui-fg-error" role="alert">{error}</Text>}
 <div className="mt-5 flex gap-3"><Button disabled={busy||!channel} onClick={()=>void load(channel,offset).catch(e=>setError(e.message))}>Refresh</Button><Text>{count} inquiries</Text></div>
 <ul className="mt-4 space-y-3">{rows.map(row=><li key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-4"><div><Text weight="plus">{row.reference}</Text><Text>{row.state} · {new Date(row.created_at).toLocaleString()}</Text><Text>{row.items.map(i=>i.title).join(', ')}</Text><Text>Advance: Rs {(row.advance_pkr-row.discount_pkr).toLocaleString()}</Text></div><Button disabled={busy} onClick={()=>void open(row.id)}>Open inquiry</Button></li>)}</ul>{!busy&&!rows.length&&<Text className="mt-5">No inquiries yet.</Text>}
 <div className="mt-4 flex gap-3"><Button disabled={busy||offset===0} onClick={()=>void load(channel,Math.max(0,offset-30)).catch(e=>setError(e.message))}>Previous</Button><Button disabled={busy||offset+rows.length>=count} onClick={()=>void load(channel,offset+30).catch(e=>setError(e.message))}>Next</Button></div>
 {selected&&<section className="mt-6 rounded border p-5"><div className="flex justify-between"><Heading level="h2">{selected.reference}</Heading><Button variant="secondary" onClick={()=>setSelected(null)}>Close details</Button></div><Text className="mt-3">Contact access is audited. CNIC is masked.</Text>{selected.customer?<dl className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(selected.customer).map(([key,value])=><div key={key}><dt className="font-medium">{key.replace(/_/g,' ')}</dt><dd className="whitespace-pre-wrap break-words">{value||'Not provided'}</dd></div>)}</dl>:<Text>Identity information has expired or was removed.</Text>}<div className="mt-4 flex flex-wrap gap-3">{(['new','contacted','closed','cancelled'] as const).map(state=><Button key={state} disabled={busy||selected.state===state} onClick={async()=>{setBusy(true);try{await api('/admin/inquiries/'+selected.id,{state,previous_state:selected.state});setSelected({...selected,state});await load(channel,offset);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Mark {state}</Button>)}</div></section>}
 </Container>;
}
export const config=defineRouteConfig({label:'Customer Inquiries'});
